//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carmax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carmaxEntities1 : DbContext
    {
        public carmaxEntities1()
            : base("name=carmaxEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactu> contactus { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<order_cars> order_cars { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<teammember> teammembers { get; set; }
    }
}
