//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carmax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teammember
    {
        public int id { get; set; }
        public string name { get; set; }
        public string images { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string link1 { get; set; }
        public string link2 { get; set; }
    }
}
